services:
  db:
    image: mysql:latest
    container_name: Group_A_project_db
    environment:
      MYSQL_USER: UMBCstudent
      MYSQL_PASSWORD: bongocat123
      MYSQL_ROOT_PASSWORD: bongocat123
      MYSQL_DB: main_project_db
    ports:
      - "3308:3306"
    volumes:
      - "./init-db:/docker-entrypoint-initdb.d"
    networks:
      - lamp-docker