services:
  db:
    image: mysql:latest
    container_name: Group_A_project_db
    environment:
      MYSQL_DATABASE: main_project_db
      MYSQL_USER: UMBCstudent
      MYSQL_PASSWORD: bongocat123
      MYSQL_ROOT_PASSWORD: bongocat123
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/libb/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - mysql_network
volumes:
  db_data:
networks:
  mysql_network: